### ISSUE TITLE
DeathStar error 

### ISSUE THREAD

**Issue by Zxxxx** [byt3bl33d3r/DeathStar#15]
## use Debian
**plz help me**

>   It's as if millions of admins suddenly cried out in terror and were suddenly silenced.
[*] Powering up the Death Star
[*] Polling for agents
[+] New Agent => Name: *.*.*.* IP: *.*.*.* HostName: *.*.*. UserName: *.*.*.*\Administrator HighIntegrity: 1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "DeathStar.py", line 538, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "DeathStar.py", line 364, in get_loggedon
    results = execute_module_with_results('powershell/situational_awareness/network/powerview/get_loggedon', agent_name, module_options)
  File "DeathStar.py", line 170, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'

<img width="994" alt="2017-06-08 4 42 32" src="https://user-images.githubusercontent.com/19280377/26920107-720d6ad0-4c6a-11e7-976f-8324f4df6c1b.png">

**Comment by NickSanzotta** [comment]
Use the forked version of Empire:
https://github.com/byt3bl33d3r/Empire

**Comment by daniel-ammann** [comment]
I'm still getting the KeyError, although I'm using the forked version.. Any idea?

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 585, in pwn_the_shit_out_of_everything
    recon(agent_name)
  File "./DeathStar.py", line 507, in recon
    domain_sid = get_domain_sid(agent_name)
  File "./DeathStar.py", line 213, in get_domain_sid
    results = execute_module_with_results('powershell/management/get_domain_sid', agent_name)
  File "./DeathStar.py", line 180, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'`

**Comment by elnerd** [comment]
Getting the same. Seems like Empire is returning a json object without the key taskID present.

**Comment by jonaslejon** [comment]
Same error here
