### ISSUE TITLE
Error reported during recon phase

### ISSUE THREAD

**Issue by urban-moniker** [byt3bl33d3r/DeathStar#17]
Hi - I'm getting the following error during the recon phase:-
```
[DEBUG] Agent: 3RA65TYC => Executed Module => success: True taskID: 4 msg: 'tasked agent 3RA65TYC to run module powershell/situational_awareness/network/powerview/get_loggedon'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 538, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "./DeathStar.py", line 373, in get_loggedon
    domain = entry.split()[1]
IndexError: list index out of range
```
Rgds

**Comment by byt3bl33d3r** [comment]
@urban-moniker hi, can you give me the raw output of the get_loggedon module?
thx

**Comment by byt3bl33d3r** [comment]
Also can you do a git pull and try again? i'm pretty sure I addresses this in 8a32b4a6ded6d85814c85bb2d68b093bf6a0c21f

**Comment by byt3bl33d3r** [comment]
Closing due to inactivity
