### ISSUE TITLE
Error on invoke_wmi (required module option missing)

### ISSUE THREAD

**Issue by utkusen** [byt3bl33d3r/DeathStar#38]
Version: Latest + Fix for TLS + Fix for "KeyID" bug

When I have 1 low integrity+1 high integrity agents (on same computer) deathstar works without a problem. However when I only got 1 low integrity agent: I got following error:

```
Agent: HMGZTF7B => Error executing module 'powershell/lateral_movement/invoke_wmi': {'error': 'required module option missing'}
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "deathstar.py", line 59, in __run
    self.__run_backup()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "deathstar.py", line 544, in spread
    invoke_wmi(agent_name, box)
  File "deathstar.py", line 468, in invoke_wmi
    results = execute_module_with_results('powershell/lateral_movement/invoke_wmi', agent_name, module_options)
  File "deathstar.py", line 180, in execute_module_with_results
    if result['taskID'] == r['taskID']:
TypeError: 'NoneType' object is not subscriptable
```

You can find full results below:
```

*] Powering up the Death Star
[*] Polling for agents
[+] New Agent => Name: HMGZTF7B IP: 192.168.1.200 HostName: HOME-PC UserName: DROP\utku HighIntegrity: 0
[*] Agent: HMGZTF7B => Starting recon
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 9 msg: 'tasked agent HMGZTF7B to run module powershell/management/get_domain_sid'
[+] Agent: HMGZTF7B => Got domain SID: S-1-5-21-1626841790-508290444-985752922
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 10 msg: 'tasked agent HMGZTF7B to run module powershell/situational_awareness/network/powerview/get_group_member'
[+] Agent: HMGZTF7B => Found 1 members of the Domain Admins group: ['DROP\\Administrator']
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 11 msg: 'tasked agent HMGZTF7B to run module powershell/situational_awareness/network/powerview/get_domain_controller'
[+] Agent: HMGZTF7B => Found 1 Domain Controllers: ['WIN-JMCGJI8UARD.drop.local']
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 12 msg: 'tasked agent HMGZTF7B to run module powershell/situational_awareness/network/powerview/user_hunter'
[+] Agent: HMGZTF7B => Found 1 active admin sessions: ['WIN-JMCGJI8UARD.drop.local']
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 13 msg: 'tasked agent HMGZTF7B to run module powershell/situational_awareness/network/powerview/get_loggedon'
[+] Agent: HMGZTF7B => Found 1 users logged into localhost: ['DROP\\utku']
[*] Agent: HMGZTF7B => Starting lateral movement
[*] Agent: HMGZTF7B => Starting domain privesc
[*] Agent: HMGZTF7B => Attempting to elevate using bypassuac_eventvwr
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 14 msg: 'tasked agent HMGZTF7B to run module powershell/privesc/gpp'
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 15 msg: 'tasked agent HMGZTF7B to run module powershell/situational_awareness/network/powerview/find_localadmin_access'
[DEBUG] Agent: HMGZTF7B => Executed Module => success: True taskID: 16 msg: 'tasked agent HMGZTF7B to run module powershell/privesc/bypassuac_eventvwr'
[+] Agent: HMGZTF7B => Found 0 GPO(s) containing credentials using GPP SYSVOL privesc
[+] New Agent => Name: GYHFMP2S IP: 192.168.1.200 HostName: HOME-PC UserName: DROP\utku HighIntegrity: 1
[DEBUG] Agent: GYHFMP2S => Executed Module => success: True taskID: 1 msg: 'tasked agent GYHFMP2S to run module powershell/situational_awareness/network/powerview/get_loggedon'
[+] Agent: GYHFMP2S => Found 1 users logged into localhost: ['DROP\\utku']
[*] Agent: GYHFMP2S => Starting domain privesc
[DEBUG] Agent: GYHFMP2S => Executed Shell Command => success: True taskID: 2
[DEBUG] Agent: GYHFMP2S => Executed Module => success: True taskID: 3 msg: 'tasked agent GYHFMP2S to run module powershell/privesc/gpp'
[+] Agent: GYHFMP2S => Enumerated 1 processes
[DEBUG] Agent: GYHFMP2S => Executed Module => success: True taskID: 4 msg: 'tasked agent GYHFMP2S to run module powershell/credentials/mimikatz/logonpasswords'
[+] Agent: GYHFMP2S => Found 0 GPO(s) containing credentials using GPP SYSVOL privesc
[+] Agent: GYHFMP2S => Executed Mimikatz
[+] Agent: HMGZTF7B => Current security context has admin access to 1 hosts
[-] Agent: HMGZTF7B => Error executing module 'powershell/lateral_movement/invoke_wmi': {'error': 'required module option missing'}
```

**Comment by utkusen** [comment]
https://github.com/byt3bl33d3r/DeathStar/pull/39 fixed it
