### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by bandrel** [byt3bl33d3r/DeathStar#4]
getting this error constantly while running Deathstar.py
```Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 533, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "./DeathStar.py", line 368, in get_loggedon
    username, domain, logon_server,_= entry.split()
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by byt3bl33d3r** [comment]
@bandrel can you give me the raw output of Empire's get_loggedon module for the host the agent is running on? this seems to be an error parsing that.
Cheers

**Comment by bandrel** [comment]
sanitized, but the format is the same.  It looks like the local accounts that are logged in are showing up so there is not a LOGON_Server.  So the method of splitting the output based on spaces wont work. 
```
Job started: 4WFBPN


wkui1_username   wkui1_logon_dom wkui1_oth_domai wkui1_logon_ser ComputerName   
                 ain             ns              ver                            
--------------   --------------- --------------- --------------- ------------   
Administrator    FAKEDOMAIN                                      localhost      
Administrator    COMPUTERNAME                                    localhost      
Administrator    .                                               localhost      
User1            FAKEDOMAIN                      DC1             localhost      
User1            FAKEDOMAIN                      DC1             localhost      
COMPITERNAME$    FAKEDOMAIN                                      localhost      





Get-NetLoggedon completed!

```

**Comment by bandrel** [comment]
Using this
```
        username = entry.split()[0]
        domain = entry.split()[1]
```
instead of this
```
        username, domain, logon_server,_= entry.split()
```

should work since that function doesnt use the logon_server anyway. 

After the change I don't see any errors so I think this should work for me.  attached PR https://github.com/byt3bl33d3r/DeathStar/pull/5
