### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 2, got 1)

### ISSUE THREAD

**Issue by phi-el** [byt3bl33d3r/DeathStar#53]
Getting the following error while executing DeathStar.py (from latest commit 6d89e7d, 4 days ago)
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 620, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "./DeathStar.py", line 404, in get_loggedon
    username, domain, *_ = entry.split()
ValueError: not enough values to unpack (expected at least 2, got 1)
```
Also, I'm getting this error later on:
```
[+] Agent: XXXXXXXXX=> Found 1 GPO(s) containing credentials using GPP SYSVOL privesc
[-] Agent: XXXXXXXXX=> Error executing module 'powershell/situational_awareness/network/powerview/get_gpo_computer': {'error': 'module name powershell/situational_awareness/network/powerview/get_gpo_computer not found'}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 564, in privesc
    computers = get_gpo_computer(agent_name, result['guid'])
  File "./DeathStar.py", line 328, in get_gpo_computer
    results = execute_module_with_results('powershell/situational_awareness/network/powerview/get_gpo_computer', agent_name, module_options)
  File "./DeathStar.py", line 181, in execute_module_with_results
    if entry['taskID'] == r['taskID']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by byt3bl33d3r** [comment]
See #54. The `get_gpo_computer` module was removed from Empire which broke everything. I submitted a PR to fix it. Hopefully will be merged soon.

Closing
