### ISSUE TITLE
get_gpo_computer question

### ISSUE THREAD

**Issue by FuckAllWorld** [byt3bl33d3r/DeathStar#61]
Env:Empire version 2.4

[-] Agent: 3AL84ZNU => Error executing module 'powershell/situational_awareness/network/powerview/get_gpo_computer': {'error': 'invalid module option'}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 564, in privesc
    computers = get_gpo_computer(agent_name, result['guid'])
  File "./DeathStar.py", line 328, in get_gpo_computer
    results = execute_module_with_results('powershell/situational_awareness/network/powerview/get_gpo_computer', agent_name, module_options)
  File "./DeathStar.py", line 181, in execute_module_with_results
    if entry['taskID'] == r['taskID']:
TypeError: 'NoneType' object is not subscriptable

**Comment by byt3bl33d3r** [comment]
See my comment [here](https://github.com/byt3bl33d3r/DeathStar/issues/54#issuecomment-428305692). Closing.
