### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by enidevops** [byt3bl33d3r/DeathStar#63]
Hi, on a freshly installed kali linux (2018.3a) i always get this error when running Deathstar (0.0.1) with Empire (2.5):

_./DeathStar.py 
[*] Powering up the Death Star
[*] Polling for agents
[+] New Agent => Name: C11C8QIO IP: 192.XXX.XXX.44 HostName: desk UserName: bob HighIntegrity: 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 616, in pwn_the_shit_out_of_everything
    recon(agent_name)
  File "./DeathStar.py", line 507, in recon
    if running_under_domain_account(agent_name):
  File "./DeathStar.py", line 680, in running_under_domain_account
    if username.split('\\')[0] != hostname and username.split('\\')[1] != 'SYSTEM':
IndexError: list index out of range_

**Comment by byt3bl33d3r** [comment]
see my answer [here](https://github.com/byt3bl33d3r/DeathStar/issues/56#issuecomment-428308101).

Cheers
