### ISSUE TITLE
Add Command to Installation on README

### ISSUE THREAD

**Issue by ghost** [byt3bl33d3r/DeathStar#69]
You should add:
cd DeathStar/
to your installation instructions.

**Comment by ReverseShellz** [comment]
Can anyone make sense of this error message?['explorer', '688', 'x64', 'DESKTOP-490F55E\\Xenon', 'Ventures', '74.51', 'MB']
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 641, in pwn_the_shit_out_of_everything
    for process in tasklist(agent_name, process='explorer'):
  File "./DeathStar.py", line 440, in tasklist
    raise
RuntimeError: No active exception to reraise
