### ISSUE TITLE
Agent Poller Error

### ISSUE THREAD

**Issue by cyberporkchopexpress** [byt3bl33d3r/DeathStar#73]
Hey! Love Deathstar and was super stoked to see the new version. Trying to run on Kali(Ubuntu) and kept throwing an agent error. Didn't know if you'd seen this before. Thanks!

`[17:29:15] INFO     [deathstar] Empire login successful                                                             deathstar.py:346
           INFO     [deathstar] Powering up the DeathStar and waiting for agents                                    deathstar.py:350
[17:29:16] ERROR    [deathstar] Agent poller errored out:                                                           deathstar.py:262
                     Traceback (most recent call last):                                                                             
                      File                                                                                                          
                    "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/deathstar.py",                  
                    line 246, in agent_poller                                                                                       
                        for agent in await self.empire.agents.get():                                                                
                      File                                                                                                          
                    "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/empire.py",                     
                    line 238, in get                                                                                                
                        r = await self.client.get("agents")                                                                         
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py",                 
                    line 1548, in get                                                                                               
                        return await self.request(                                                                                  
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py",                 
                    line 1371, in request                                                                                           
                        response = await self.send(                                                                                 
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py",                 
                    line 1406, in send                                                                                              
                        response = await self._send_handling_auth(                                                                  
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py",                 
                    line 1444, in _send_handling_auth                                                                               
                        response = await self._send_handling_redirects(                                                             
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py",                 
                    line 1476, in _send_handling_redirects                                                                          
                        response = await self._send_single_request(request, timeout)                                                
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py",                 
                    line 1502, in _send_single_request                                                                              
                        (status_code, headers, stream, ext,) = await transport.arequest(                                            
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/co                 
                    nnection_pool.py", line 208, in arequest                                                                        
                        connection = await self._get_connection_from_pool(origin)                                                   
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/co                 
                    nnection_pool.py", line 248, in _get_connection_from_pool                                                       
                        if connection.is_socket_readable():                                                                         
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/co                 
                    nnection.py", line 168, in is_socket_readable                                                                   
                        return self.connection is not None and self.connection.is_socket_readable()                                 
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/ht                 
                    tp11.py", line 205, in is_socket_readable                                                                       
                        return self.socket.is_readable()                                                                            
                      File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_backends                 
                    /asyncio.py", line 182, in is_readable                                                                          
                        return is_socket_readable(sock.fileno())                                                                    
                    AttributeError: 'NoneType' object has no attribute 'fileno'                                                     
                                                                                                                                    
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/deathstar.py", line 72, in planetary_recon
    for agent in await self.empire.agents.get():
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/empire.py", line 238, in get
    r = await self.client.get("agents")
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py", line 1548, in get
    return await self.request(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py", line 1371, in request
    response = await self.send(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 208, in arequest
    connection = await self._get_connection_from_pool(origin)
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 248, in _get_connection_from_pool
    if connection.is_socket_readable():
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/connection.py", line 168, in is_socket_readable
    return self.connection is not None and self.connection.is_socket_readable()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_async/http11.py", line 205, in is_socket_readable
    return self.socket.is_readable()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/httpcore/_backends/asyncio.py", line 182, in is_readable
    return is_socket_readable(sock.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/deathstar", line 8, in <module>
    sys.exit(run())
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/deathstar.py", line 385, in run
    asyncio.run(main(args))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/deathstar.py", line 352, in main
    await deathstar.power_up()
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/deathstar.py", line 334, in power_up
    await asyncio.gather(*[
  File "/root/.local/pipx/venvs/deathstar-empire/lib/python3.8/site-packages/deathstar/deathstar.py", line 111, in planetary_recon
    log.error(f"Planetary recon for agent {agent.name} errored out:\n {tb}")
UnboundLocalError: local variable 'agent' referenced before assignment`

**Comment by f1se4** [comment]
Same issue Pentesting our systems.
Empire - up
DeathStar - up (installed through pip)
Executed CrackMapExec with known user/password --Z ok

Then same error than above.
