### ISSUE TITLE
unicode username causing issue

### ISSUE THREAD

**Issue by stboch** [byt3bl33d3r/DeathStar#8]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "DeathStar.py", line 512, in privesc
    for result in gpp(agent_name):
  File "DeathStar.py", line 327, in gpp
    usernames = list(map(str.strip, entry.split(':')[1].strip().split(',')))
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'

**Comment by stboch** [comment]
This maybe an issue that I was running as Python2 rerunning as python3

**Comment by byt3bl33d3r** [comment]
If you were running it with Python 2 that's probably the issue then.
If it still happens in Python 3 let me know.
